services:
  vdb-demo-fe:
    image: h-alice/vdb-demo:latest
    depends_on:
      - retrieve-service
    restart: unless-stopped
    networks:
      - internal
      - gateway
    environment:
      RETRIEVAL_ENDPOINT: "http://retrieve-service:3000/retrieval"
      __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "doit-gpu-node1.gov.taipei"
    command:
      - npm
      - run
      - dev
      
networks:
  gateway:
    external: true
    name: gateway
